language: python
python:
  - 2.6
  - 2.7
notifications:
  irc: "irc.freenode.org#nens"
  email: false
before_install:
  - sudo apt-get git mercurial bzr
install:
  - python bootstrap.py
  - bin/buildout -v
script:
  - bin/test
