language: python
python:
  - 2.6
  - 2.7
before_install:
  - sudo apt-get install python-psycopg2
notifications:
  irc: "irc.freenode.org#nens"
  email: false
install:
  - python bootstrap.py
  - bin/buildout -v
script:
  - bin/test
